version: "3"
services:
  portfolio_db:
    restart: always
    container_name: portfolio_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=portfolio_admin
      - POSTGRES_PASSWORD=NijO9JasFfaBZgKvA
      - POSTGRES_DB=portfolio_db
    image: postgres:15.4-alpine3.17
    networks:
      - app-network

  # frontend:
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - backend
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "20m"
  #       max-file: "3"

  # nginx:
  #   restart: always
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - app-network
  #   depends_on:
  #     - frontend

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:
