import AuthControl from '@/components/AuthControl/AuthControl';
import { getServerSession } from 'next-auth';
import { Montserrat } from 'next/font/google';
import { authOptions } from '../api/auth/[...nextauth]/handler';
const montserrat = Montserrat({ subsets: ['latin'] });
import './ShopLayout.scss';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <div className="shop-layout">
          <AuthControl session={session} />
          <main className="shop-layout__page">{children}</main>
        </div>
      </body>
    </html>
  )
}
